### PR TITLE
Do more conservative URL normalization

### LINKED ISSUE #654: Encoded plus (+) %2B in path segment somehow not working
I have an S3 path that has a "+" in it, so it's encoded URI ends up with a "%2B" in it.  Specifically, the S3 key is "A+B.txt", so the working S3 URL is -- and this is an actual working public URL that demonstrates it -- `https://scih-data-dev.s3.amazonaws.com/A%2BB.txt`

You can see you can access it with your browser, it's a file that just includes the string "content\n". 

It can also be accessed with net::http:

```
irb(main):089:0> Net::HTTP.get(URI.parse("https://scih-data-dev.s3.amazonaws.com/A%2BB.txt"))
=> "content\n"
```

No problem. It can also be accessed via curl, for what it's worth. `curl "https://scih-data-dev.s3.amazonaws.com/A%2BB.txt"`

When I try to get it via http-rb however, S3 returns a 403 error. 

```
irb(main):098:0> HTTP.get("https://scih-data-dev.s3.amazonaws.com/A%2BB.txt")
=> #<HTTP::Response/1.1 403 Forbidden {"X-Amz-Request-Id"=>"BF0W8PB090MAQW5B", "X-Amz-Id-2"=>"BTkuhpvYFsvHKdudR4W/tYNKhlq9I0LG188oWJ2MHLih7MErl32414MzRz7tpSGnQec134oVcYo=", "Content-Type"=>"application/xml", "Transfer-Encoding"=>"chunked", "Date"=>"Mon, 22 Mar 2021 21:02:57 GMT", "Server"=>"AmazonS3", "Connection"=>"close"}>
```

I think http-rb is doing something weird with escaping/unescaping there and requesting a different URL, which would then return a 403 from S3.    I haven't debugged further this this yet, I'm not sure exactly what HTTP request is being made to the server -- but apparently not the right one, since all those other tools can retrieve this url?

Is there a bug of some kind when the URL contains `%2B`?

### PR DESCRIPTION
**Pull request by c960657**
http.rb normalises URLs before making a request. This normalisation may reformat a perfectly valid URL. Even though the normalised URL in theory is equivalent to the original URL, some servers may not recognise this (see e.g. https://github.com/mastodon/mastodon/pull/26219).

Some of these problems are due to a bug in Addressable (see https://github.com/sporkmonger/addressable/issues/366). But even with that bug fixes, there is no reason to normalise the URL before fetching it, apart from fixing obviously invalid aspects such as spaces in the path. There is no benefit, only potential problems.

I suggest we take a more conservative approach and only escape characters in path and query outside the printable ASCII range, and never decode any existing percent-escape sequences. This is the [approach taken by cURL](https://github.com/curl/curl/blob/master/docs/URL-SYNTAX.md), so that seems like a safe bet.

If somebody wants more “aggressive” normalisation for better caching in HTTP proxies or whatever, and they are aware of the risks connected with this, they can provide a custom normaliser or just call `Addressable::URI#normalize` before invoking htp.rb. But I don't think such potentially risky behaviour should be the default.

Fixes #654

### CODE REVIEW

File: spec/lib/http/uri_spec.rb [hunk 1]
```diff
@@ -11,6 +11,92 @@
   subject(:https_uri) { described_class.parse(example_https_uri_string) }
   subject(:ipv6_uri) { described_class.parse(example_ipv6_uri_string) }
 
+  describe "NORMALIZER" do
```
Comment (ixti) [inline spec/lib/http/uri_spec.rb:14]: Can you please move it to a separate spec file `spec/lib/http/uri/normalizer_spec.rb` instead? So it will look like:

``` ruby
RSpec.describe HTTP::URI::NORMALIZER do
  ...
end
```

File: lib/http/uri.rb [hunk 2]
```diff
@@ -71,6 +74,16 @@ def self.form_encode(form_values, sort = false)
       Addressable::URI.form_encode(form_values, sort)
     end
 
+    # Percent-encode all characters matching a regular expression.
+    #
+    # @param [String] string raw string
+    # @param [Regexp] pattern regular expression matching characters to percent-encode
+    #
+    # @return [String] encoded value
+    def self.percent_encode(string, pattern)
```
Comment (ixti) [inline lib/http/uri.rb:83]: I think `pattern` argument is not needed here.

**Review by ixti — CHANGES_REQUESTED** [review]
Thank you! This is great. Can you please move NORMALIZER proc spec in a separate file though, to follow RSpec naming conventions? And, please, add `@private` documentation tag to `self.percent_encode`

**Comment by c960657** [comment]
Done :-)

**Review by tarcieri — APPROVED** [review]
